### ISSUE TITLE
Have you considered using PokeApiNet?

### ISSUE THREAD

**Issue by Julian-Mostbauer** [lGruenzweilHTL/WMC-Pokedex#7]
Seems useful for your backend
https://github.com/jtwotimes/PokeApiNet

**Comment by Julian-Mostbauer** [comment]
@lGruenzweilHTL

**Comment by lGruenzweilHTL** [comment]
Terribly sorry for the late answer. I have indeed considered using this API Wrapper but I thought it wasn't worth it to change all my code.
This opinion has changed now, that the generator needs some more optimization. I will try to integrate PokeApiNet into the generator and run some efficiency tests.
Thank you for your suggestion, but for more suggestions regarding the backend, please refer to the [repo of the generator](https://github.com/lGruenzweilHTL/Pokedex-Generator).
